// Generated by CoffeeScript 1.10.0

/* app.coffee */

(function() {
  var app, bodyparser, express, path, server;

  path = require('path');

  express = require('express');

  app = exports.app = express();

  app.use(express["static"](path.join(__dirname, 'public')));

  app.set('view engine', 'jade');

  app.use(require('express-session')({
    secret: require('node-uuid').v4(),
    resave: true,
    saveUninitialized: true
  }));

  app.use(require('cookie-parser')());

  bodyparser = require('body-parser');

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded({
    extended: true
  }));

  app.use('/', require('./routes'));

  app.set('port', process.env.PORT || 5000);

  server = exports.server = app.listen(app.get('port'), function() {
    var host, port;
    host = server.address().address;
    port = app.get('port');
    return console.log("Application server running at http://" + host + ":" + port);
  });

  require('./server');

}).call(this);
