// Generated by CoffeeScript 1.10.0

/* src/models.js */

(function() {
  var Board, Sticky;

  Sticky = (function() {
    Sticky.prototype.text = '';

    function Sticky(id1, x1, y1) {
      this.id = id1;
      this.x = x1;
      this.y = y1;
    }

    return Sticky;

  })();

  exports.Board = Board = (function() {
    Board.prototype.maxId = 0;

    Board.prototype.stickyList = [];

    function Board(fingerprint, name, cleanname) {
      this.fingerprint = fingerprint;
      this.name = name;
      this.cleanname = cleanname;
    }

    Board.prototype.addSticky = function(x, y) {
      var sticky;
      sticky = new Sticky(this.maxId++, x, y);
      this.stickyList.push(sticky);
      return sticky;
    };

    Board.prototype.removeSticky = function(identifier) {
      if (typeof identifier === 'number') {
        return this.removeSticky(this.getSticky(identifier));
      } else {
        return this.stickyList.splice(this.stickyList.indexOf(identifier), 1);
      }
    };

    Board.prototype.getSticky = function(id) {
      var sticky;
      return ((function() {
        var i, len, ref, results;
        ref = this.stickyList;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          sticky = ref[i];
          if (sticky.id === id) {
            results.push(sticky);
          }
        }
        return results;
      }).call(this))[0];
    };

    return Board;

  })();

}).call(this);
