// Generated by CoffeeScript 1.10.0

/* routes.coffee */

(function() {
  var router;

  router = require('express').Router();

  router.get('/', function(req, res) {
    return res.redirect('/scrumbr');
  });

  router.get('/start', function(req, res) {
    return res.render('start');
  });

  router.get('/scrumbr', function(req, res) {
    return res.render('scrumbr');
  });

  module.exports = router;

}).call(this);
