// Generated by CoffeeScript 1.10.0

/* src/server.js */

(function() {
  var express, path;

  path = require('path');

  express = require('express');

  require('mongodb').MongoClient.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/scrumtious', function(err, database) {
    var app, bodyparser;
    if (err) {
      console.log(err);
      process.exit(1);
    }
    exports.db = database;
    console.log('Database connection ready');
    app = express();
    app.use(express["static"](path.join(__dirname, 'public')));
    app.set('view engine', 'jade');
    app.use(require('express-session')({
      secret: require('node-uuid').v4(),
      resave: true,
      saveUninitialized: true
    }));
    app.use(require('cookie-parser')());
    bodyparser = require('body-parser');
    app.use(bodyparser.json());
    app.use(bodyparser.urlencoded({
      extended: true
    }));
    app.use('/', require('./routes'));
    app.set('port', process.env.PORT || 5000);
    exports.server = app.listen(app.get('port'));
    console.log('Server running');
    return require('./socket');
  });

}).call(this);
