// Generated by CoffeeScript 1.10.0

/* socket.js */

(function() {
  var boards, io;

  io = require('socket.io')(require('./server').server);

  boards = require('./server').db.collection('boards');

  io.on('connect', function(socket) {
    socket.on('HANDSHAKE', function(fingerprint) {
      return boards.findOne({
        fingerprint: fingerprint
      }, function(err, item) {
        return socket.emit('INITIALIZE', item);
      });
    });
    return socket.on('CLOSE', function(payload) {
      return boards.update({
        fingerprint: payload.fingerprint
      }, {
        $set: {
          stickyData: payload.stickyData
        }
      });
    });
  });

}).call(this);
